#pragma once

/**
 * @brief Enumeration of every render model in the game.
 */
enum class ModelType {
	Cube,
	PlayerFire,
	PlayerLightning,
	PlayerWater,
	WarrenBear,
	HealthPotion,
	InvisibilityPotion,
    Torchlight,
	NauseaPotion,
	InvincibilityPotion,
	FireSpell,
	HealSpell,
	TeleportSpell,
	Frame,
	Orb,
	FloorSpikeHorizontal,
	FloorSpikeVertical,
    FloorSpikeFull,
	LavaCross,
    LavaHorizontal,
    LavaVertical,
	ArrowTrapUp,
	ArrowTrapDown,
	ArrowTrapLeft,
	ArrowTrapRight,
	SpikeTrap,
	TeleporterTrap,
	Dagger,
	Sword,
	Hammer,
	Lightning,
    Arrow,
    ArrowTrap,
	FireballTrapLeft,
	FireballTrapRight,
	FireballTrapUp,
	FireballTrapDown,
	SunGod,
	Mirror,
	LightCut
};