name: Build

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  client-windows:
    name: Client on Windows 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake -G "Visual Studio 17 2022" ..
    - name: Build
      run: cd build && make client
  client-linux:
    name: Client on Linux (Ubuntu) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Build
      run: cd build && make client
  server-windows:
    name: Server on Windows 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake -G "Visual Studio 17 2022" ..
    - name: Build
      run: cd build && make server 
  server-linux:
    name: Server on Linux (Ubuntu) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Build
      run: cd build && make server 
