name: Build Client

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  windows:
    name: Build on Windows 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Build
      run: make client
  linux:
    name: Build on Linux (Ubuntu) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Build
      run: make client
