name: Build

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  client-windows:
    name: Client on Windows 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0
    - name: Run CMake
      run: cd build && cmake -G "Ninja" ..
    - name: Test Directory 1
      if: always()
      run: ls
    - name: Test Directory 2
      if: always()
      run: ls build
    - name: Test Directory 3
      if: always()
      run: ls out
    - name: Build in build/
      if: always()
      run: cd build && ninja client
    - name: Build in out/build/x64-Debug
      if: always()
      run: cd ouht/build/x64-Debug && ninja client
  client-linux:
    name: Client on Linux (Ubuntu) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Build
      run: cd build && make client
  server-windows:
    name: Server on Windows 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake -G "Visual Studio 17 2022" ..
    - name: Build
      run: cd build && make server 
  server-linux:
    name: Server on Linux (Ubuntu) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Build
      run: cd build && make server 
