name: Build

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  client-windows:
    name: Client on Windows 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake -G "Ninja" -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl ..
    - name: Build
      run: cd build && ninja client
  client-linux:
    name: Client on Linux (Ubuntu) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Build
      run: cd build && make client
  server-windows:
    name: Server on Windows 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake -G "Ninja" -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl ..
    - name: Build
      run: cd build && ninja server
  server-linux:
    name: Server on Linux (Ubuntu) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Build
      run: cd build && make server 
