name: Add issues to repo project 

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/ucsd-cse125-sp24/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
