name: Lint

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  cppcheck:
    name: cppcheck 
    runs-on: ubuntu-latest
    steps:
    - name: Install CppCheck
      run: sudo apt-get update && sudo apt-get install cppcheck
    - name: CppCheck version 
      run: cppcheck --version
    - name: Install OpenGL
      run: sudo apt-get update && sudo apt-get install --fix-missing cmake pkg-config mesa-utils libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev libxkbcommon-dev libxinerama-dev libxcursor-dev libxi-dev xvfb
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Lint
      run: cd build && make lint 
