name: Lint

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: clang-tidy version
      run: clang-tidy --version 
    - name: Lint
      run: cd build && make lint 
