name: Lint

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  cppcheck:
    name: cppcheck 
    runs-on: ubuntu-latest
    steps:
    - name: Install CppCheck
      run: apt-get update && apt-get install cppcheck
    - uses: actions/checkout@v4
    - name: Create build dir
      run: mkdir -p build
    - name: Run CMake
      run: cd build && cmake ..
    - name: Lint
      run: cd build && make lint 
